# Generated by Django 4.2.20 on 2025-03-16 21:53

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='nota',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[catalog.models.validar_nota]),
        ),
        migrations.AddConstraint(
            model_name='estudiante',
            constraint=models.UniqueConstraint(fields=('primer_nombre', 'apellido'), name='unique_estudiante'),
        ),
    ]
